default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kadai_app_development

test:
  <<: *default
  database: kadai_app_test

production:
  <<: *default
  database: kadai_app_production
  username: kadai_app
  password: <%= ENV['KADAI_APP_DATABASE_PASSWORD'] %>
